name: jinjin's devlog
description:
meta_description:

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https://myjinjin.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "jinjin"

# Disqus config
disqus-shortname: ""
